### ISSUE TITLE
Remoteform and Drupal8

### ISSUE THREAD

**Issue by mlutfy** [progressivetech/net.ourpowerbase.remoteform#22]
This one particularly confused me, so maybe it can help others:

To my understanding, Drupal8 handles CORS rather differently that Drupal7:  
https://www.drupal.org/node/2715637

To get remoteform to work, I had to do the following to the `services.yml` of my site (in `sites/default/services.yml`)

```
---

parameters:

  cors.config:
    enabled: true
    # Specify allowed headers, like 'x-allowed-header'.
    allowedHeaders: ['content-type', 'authorization']
    # Specify allowed request methods, specify ['*'] to allow all possible ones.
    allowedMethods: ['GET', 'POST']
    # Configure requests allowed from specific origins.
    allowedOrigins: ['https://www.example.org']
    # Sets the Access-Control-Expose-Headers header.
    exposedHeaders: false
    # Sets the Access-Control-Max-Age header.
    maxAge: false
    # Sets the Access-Control-Allow-Credentials header.
    supportsCredentials: false
```

then flush cache (`drush cr`).

**Comment by jmcclelland** [comment]
Thank you for posting this! We should figure out a way to include this in the docs.

**Comment by JoeMurray** [comment]
Maybe even make it a mini-contrib module for the D8 remote site.

**Comment by mlutfy** [comment]
Mikey on [the chat](https://chat.civicrm.org/civicrm/pl/exdhko8qip83zqpkytaezpg8ah) sent me this link :  
https://www.drupal.org/docs/drupal-apis/services-and-dependency-injection/altering-existing-services-providing-dynamic

**Comment by jackrabbithanna** [comment]
We've had to do that exact same thing in a services.yml file for one site
You can give services settings in a module_name.services.yml file

in a custom module, say custom_cors
custom_cors.services.yml
change your settings to what you want here
```
parameters:
  cors.config:
    enabled: true
    # Specify allowed headers, like 'x-allowed-header'.
    allowedHeaders: ['Content-type']
    # Specify allowed request methods, specify ['*'] to allow all possible ones.
    allowedMethods: ['*']
    # Configure requests allowed from specific origins.
    allowedOrigins: []
    # Sets the Access-Control-Expose-Headers header.
    exposedHeaders: false
    # Sets the Access-Control-Max-Age header.
    maxAge: 3600
    # Sets the Access-Control-Allow-Credentials header.
    supportsCredentials: true

```
If you want to override the cors service use a Service provider / Service Modifier, can really do anything you want by overriding the different methods.

in a src/CustomCorsServiceProvider.php

```
<?php

namespace Drupal\custom_cors;

use Drupal\Core\DependencyInjection\ContainerBuilder;
use Drupal\Core\DependencyInjection\ServiceProviderBase;


/**
 * Alter the service container to use a custom class.
 */
class CustomCorsServiceProvider implements ServiceProviderBase {

  /**
   * {@inheritdoc}
   *
   * Overrides the CORS service (http_middleware.cors) to change some
   * functionality.
   */
  public function alter(ContainerBuilder $container) {
    $container->getDefinition('http_middleware.cors')->setClass(CustomCors::class);
  }
}

```

Then a service class, in src/CustomCors.php
```
<?php

namespace Drupal\custom_cors;

use Asm89\Stack\Cors;
use Symfony\Component\HttpKernel\HttpKernelInterface;

/**
 * Add Allowed Origins white listed domains list
 */
class CustomCors extends Cors {
// do cool custom stuff
```
